### ISSUE TITLE
dialogue box before ban

### ISSUE THREAD

**Issue by Ne-Row** [Oakraven79/pavlov_rcon_tcl#1]
Hello! Love the plugin! It sometimes is easy to accidentally ban someone in VR. Would it be possible to add a confirmation dialogue box when banning someone? a popup like... "Are you sure you want to ban "clientname?" with an option "Yes" or "Cancel"

**Comment by Oakraven79** [comment]
Noted, will add.

**Comment by Oakraven79** [comment]
Resolved with 0.76 release ( https://github.com/Oakraven79/pavlov_rcon_tcl/releases/tag/0.76 )
