### ISSUE TITLE
Suggestion: Add Official TTT Gamemode to Switch map dropdown.

### ISSUE THREAD

**Issue by Dentora** [Oakraven79/pavlov_rcon_tcl#6]
As of update 26 TTT is a official gamemode that can load on any map, Would be useful to have the Option available on the Switch map gamemode dropdown menu.

**Comment by Oakraven79** [comment]
Oh sweet. Thank you for the update. Will add shortly

**Comment by Oakraven79** [comment]
Added in 0.66 

https://github.com/Oakraven79/pavlov_rcon_tcl/releases/download/0.66/pavlov_rcon_tcl-0-66.zip
