### ISSUE TITLE
Editable json for new gamemodes

### ISSUE THREAD

**Issue by lipide512** [Oakraven79/pavlov_rcon_tcl#8]
Hi ! Thanks for ths very usefull piece of software !
May be, it should be interesting to put gamemodes in a separate json to be free to edit it and avoid to wait minor update to fix new mode in selection ?
Thanks for your work  !

**Comment by Oakraven79** [comment]
Hey!

Good idea. I'm just adding the extra game modes now but will also add a gamemodes.json that can override. 

Cheers

**Comment by Oakraven79** [comment]
Resolved in https://github.com/Oakraven79/pavlov_rcon_tcl/releases/tag/0.75

**Comment by kw64** [comment]
Great ! Already downloaded and used ! :) 
Another idea ... a "maintenance" option with auto-timer, to command on a fresh setup of the server to rotate maplist automatically to preload ou update all maps. On use, the script launch the first map, when server start a game after updating, the script detect the state of the map then launch the next map..etc.. very usefull with poor internet connection to avoid preloading time during game sessions. thanks ! :)

**Comment by kw64** [comment]
A little issue with the new json file. In the release package, you reverse "one in the chamber" text with rcon command. 
    "OITC": "One In The Chamber",
should be :
    "One In The Chamber": "OITC",
When rcon command is unrecognized, its totally freeze the pavlov clients - can't show or exit game menu... have to kick from server. Thanks !
ps : i'm lipide512 - connected on my second pc. :)

**Comment by Oakraven79** [comment]
Good spot thank you!  I'll make the change now

**Comment by Oakraven79** [comment]
I'll have a think about the maintenance suggestion. The complexity there is that the RCON interface doesn't give away too much of the server's current state and also if the server is doing something like downloading a map it hasn't been clear in the past that it is doing that. There may have been changes so i'll look into it when i can, cheers

**Comment by Oakraven79** [comment]
Have edited the release https://github.com/Oakraven79/pavlov_rcon_tcl/releases/tag/0.75 with the game_modes fix
